language: python
python:
  - 2.7
  - 3.4
install:
  - sudo apt-get -y update
  # install R
  - sudo apt-get -y update
  - sudo apt-get -y install r-base
  - sudo apt-get -y install python-matplotlib
  # make bedtools from source
  - sudo wget https://github.com/arq5x/bedtools2/releases/download/v2.25.0/bedtools-2.25.0.tar.gz
  - sudo tar -zxvf bedtools-2.25.0.tar.gz
  - cd bedtools2
  - sudo make
  - sudo cp bin/*  /usr/local/bin/
  - cd ..

  #- sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
  #- pip install 
  # Install conda
  #- sudo -H pip install conda
  - sudo -H pip install auxlib
  - sudo -H pip install conda
  # install deps
  #- sudo -H conda init
  - sudo -H conda init
  #- conda install -c r r
  #- sudo -H conda update conda --yes
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  - pip install codecov
  # install your own package into the environment
  - python setup.py install
  - pip install -r requirements.txt
  # install R components
  - sudo R -f inferelator_ng/R_code/packages.R
script:
  - python -c "import os; print(repr(os.name))"
  - python -c "import matplotlib.pyplot as plt; print('imported '+plt.__file__)"
  - coverage run --source=inferelator_ng setup.py test
  #- nosetests
after_success:
  - codecov
after_failure:
  - pwd
  - find .
  - cat ./inferelator_ng/tests/artifacts/run_mi.R
  - R -f ./inferelator_ng/tests/artifacts/run_mi.R
